development:
  host: 127.0.0.1
  port: 6379

test:
  host: 127.0.0.1
  port: 6379

staging:
  host: limoneno-testing-001.tmcxaq.0001.use1.cache.amazonaws.com
  port: 6379

production:
  host: limoneno-testing-001.tmcxaq.0001.use1.cache.amazonaws.com
  port: 6379