version: '3.5'
services:
  limoneno-frontend:
    image: 786298960439.dkr.ecr.us-east-1.amazonaws.com/limoneno-frontend
    networks:
      - traefik-net
    deploy:
      labels:
        traefik.enable: "true"
        traefik.port: 80
        traefik.frontend.redirect.entryPoint: "https"
        traefik.docker.network: traefik-net
        traefik.frontend.rule: "Host:limoneno.lemontech.com"
  limoneno-backend:
    image: 786298960439.dkr.ecr.us-east-1.amazonaws.com/limoneno-backend
    networks:
      - traefik-net
    deploy:
      labels:
        traefik.enable: "true"
        traefik.port: 5000
        traefik.frontend.redirect.entryPoint: "https"
        traefik.docker.network: traefik-net
        traefik.frontend.rule: "Host:api.limoneno.lemontech.com"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: limoneno-testing.ccvvg39btzna.us-east-1.rds.amazonaws.com
    networks:
      - traefik-net
    deploy:
      labels:
        traefik.enable: "true"
        traefik.port: 80
        traefik.frontend.redirect.entryPoint: "https"
        traefik.docker.network: traefik-net
        traefik.frontend.rule: "Host:db.limoneno.lemontech.com"
networks:
  traefik-net:
    external: true